/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Database constructor options */
export interface DatabaseOptions {
  readonly?: boolean
  fileMustExist?: boolean
  timeout?: number
}
/** Progress information for database backup */
export interface BackupProgress {
  totalPages: number
  remainingPages: number
}
/** Column information from Statement#columns() */
export interface ColumnInfo {
  name: string
  column?: string
  table?: string
  database?: string
  type?: string
}
/** Result of running a statement. */
export interface RunResult {
  changes: number
  lastInsertRowid: number
}
/** SqliteError for compatibility with better-sqlite3 */
export declare class SqliteError {
  message: string
  code: string
}
/**
 * A SQLite database connection with transparent Noria acceleration.
 * API compatible with better-sqlite3.
 */
export declare class Database {
  /**
   * Create a new database connection.
   * @param filename - Path to database file, or ':memory:' for in-memory database
   * @param options - Optional configuration object
   */
  constructor(filename?: string | undefined | null, options?: DatabaseOptions | undefined | null)
  /** The filename passed to the constructor. */
  get name(): string
  /** Whether the database is open. */
  get open(): boolean
  /** Whether the database is in-memory. */
  get memory(): boolean
  /** Whether the database is read-only. */
  get readonly(): boolean
  /** Whether the database is currently in a transaction. */
  get inTransaction(): boolean
  /** Prepare a SQL statement. */
  prepare(sql: string): Statement
  /**
   * Execute one or more SQL statements.
   * Note: Returns void in Rust; JavaScript wrapper handles chaining.
   */
  _exec(sql: string): void
  /** Close the database connection. */
  close(): void
  /**
   * Toggle unsafe mode.
   * In unsafe mode, operations that would normally be blocked during iteration are allowed.
   * @param enabled - Whether to enable unsafe mode. If not provided, returns current state.
   */
  _unsafeMode(enabled?: boolean | undefined | null): boolean
  /**
   * Toggle default safe integers mode.
   * When enabled, new statements will return integers as BigInt by default.
   * @param enabled - Whether to enable safe integers. If not provided, returns current state.
   */
  _defaultSafeIntegers(enabled?: boolean | undefined | null): boolean
  /** Get the default safe integers setting. */
  _getDefaultSafeIntegers(): boolean
  /** Load a SQLite extension. */
  _loadExtension(path: string, entryPoint?: string | undefined | null): void
  /**
   * Perform a simple backup of the database using VACUUM INTO.
   * This is a synchronous operation that creates a complete copy of the database.
   * For incremental backup with progress callbacks, a more sophisticated implementation
   * using rusqlite's backup API would be needed.
   */
  _backup(destPath: string, attachedName?: string | undefined | null): BackupProgress
  /**
   * Serialize the database to a Buffer.
   * Returns the raw database bytes as a Node.js Buffer.
   */
  _serialize(attachedName?: string | undefined | null): Buffer
  /**
   * Register a user-defined SQL function.
   * @param fn - JavaScript function to call
   * @param name - SQL function name
   * @param argc - Number of arguments (-1 for varargs)
   * @param safe_ints - Whether to use BigInt for integers (0=false, 1=true, 2=inherit)
   * @param deterministic - Whether function is deterministic
   * @param direct_only - Whether function can only be called directly (not from triggers/views)
   *
   * This uses raw NAPI calls similar to how better-sqlite3 uses raw V8 calls.
   * Since SQLite runs on the main Node.js thread, we can call JS functions
   * directly without ThreadsafeFunction.
   */
  _registerFunction(callback: (...args: any[]) => any, name: string, argc: number, safeInts: number, deterministic: boolean, directOnly: boolean): void
  /**
   * Register a user-defined aggregate function.
   * @param start - Initial accumulator value (or function that returns initial value)
   * @param step - Function called for each row: step(accumulator, ...values)
   * @param inverse - Optional function for window functions: inverse(accumulator, ...values)
   * @param result - Optional function to transform final result: result(accumulator)
   * @param name - SQL function name
   * @param argc - Number of arguments (-1 for varargs)
   * @param safe_ints - Whether to use BigInt for integers (0=false, 1=true, 2=inherit)
   * @param deterministic - Whether function is deterministic
   * @param direct_only - Whether function can only be called directly
   */
  _registerAggregate(start: unknown, step: (acc: any, ...args: any[]) => any, inverse: (...args: any[]) => any | undefined | null, resultFn: (...args: any[]) => any | undefined | null, name: string, argc: number, safeInts: number, deterministic: boolean, directOnly: boolean): void
}
/** A prepared SQL statement. */
export declare class Statement {
  /** Whether this statement returns data (is a SELECT or has RETURNING). */
  get reader(): boolean
  /** The source SQL string. */
  get source(): string
  /**
   * Execute the statement and return the first row.
   * Throws if this is not a reader statement.
   */
  get(...params: any[]): any | null
  /** Execute the statement and return all rows. */
  all(...params: any[]): Array<any>
  /** Execute the statement and return info about the execution. */
  run(...params: any[]): RunResult
  /** Enable pluck mode - return only the first column value. */
  pluck(enabled?: boolean | undefined | null): this
  /** Enable expand mode - group columns by table. */
  expand(enabled?: boolean | undefined | null): this
  /** Enable raw mode - return rows as arrays. */
  raw(enabled?: boolean | undefined | null): this
  /** Enable safe integers mode - return integers as BigInt. */
  _safeIntegers(enabled?: boolean | undefined | null): this
  /** Bind parameters permanently for reuse. */
  bind(...params: any[]): this
  /**
   * Get column information for this statement.
   * Note: SQLite column origin info requires SQLITE_ENABLE_COLUMN_METADATA which
   * may not be available. We return basic column names for now.
   */
  columns(): Array<ColumnInfo>
}
