/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Database constructor options */
export interface DatabaseOptions {
  readonly?: boolean
  fileMustExist?: boolean
  timeout?: number
}
/** Column information from Statement#columns() */
export interface ColumnInfo {
  name: string
  column?: string
  table?: string
  database?: string
  type?: string
}
/** Result of running a statement. */
export interface RunResult {
  changes: number
  lastInsertRowid: number
}
/** SqliteError for compatibility with better-sqlite3 */
export declare class SqliteError {
  message: string
  code: string
}
/**
 * A SQLite database connection with transparent Noria acceleration.
 * API compatible with better-sqlite3.
 */
export declare class Database {
  /**
   * Create a new database connection.
   * @param filename - Path to database file, or ':memory:' for in-memory database
   * @param options - Optional configuration object
   */
  constructor(filename?: string | undefined | null, options?: DatabaseOptions | undefined | null)
  /** The filename passed to the constructor. */
  get name(): string
  /** Whether the database is open. */
  get open(): boolean
  /** Whether the database is in-memory. */
  get memory(): boolean
  /** Whether the database is read-only. */
  get readonly(): boolean
  /** Whether the database is currently in a transaction. */
  get inTransaction(): boolean
  /** Prepare a SQL statement. */
  prepare(sql: string): Statement
  /**
   * Execute one or more SQL statements.
   * Note: Returns void in Rust; JavaScript wrapper handles chaining.
   */
  _exec(sql: string): void
  /** Close the database connection. */
  close(): void
  /** Load a SQLite extension. */
  _loadExtension(path: string, entryPoint?: string | undefined | null): void
}
/** A prepared SQL statement. */
export declare class Statement {
  /** Whether this statement returns data (is a SELECT or has RETURNING). */
  get reader(): boolean
  /** The source SQL string. */
  get source(): string
  /**
   * Execute the statement and return the first row.
   * Throws if this is not a reader statement.
   */
  get(...params: any[]): any | null
  /** Execute the statement and return all rows. */
  all(...params: any[]): Array<any>
  /** Execute the statement and return info about the execution. */
  run(...params: any[]): RunResult
  /** Enable pluck mode - return only the first column value. */
  pluck(enabled?: boolean | undefined | null): this
  /** Enable expand mode - group columns by table. */
  expand(enabled?: boolean | undefined | null): this
  /** Enable raw mode - return rows as arrays. */
  raw(enabled?: boolean | undefined | null): this
  /** Bind parameters permanently for reuse. */
  bind(...params: any[]): this
  /**
   * Get column information for this statement.
   * Note: SQLite column origin info requires SQLITE_ENABLE_COLUMN_METADATA which
   * may not be available. We return basic column names for now.
   */
  columns(): Array<ColumnInfo>
}
